### ISSUE TITLE
cmake issues

### ISSUE THREAD

**Issue by r9guy** [rtlabs-com/m-bus#3]
CMAKE is unable to generate configuration in Visual Studio.

on lines 85,84,86

> `[CMake] CMake Error at C:\Users\arsha\Source\Repos\m-bus\CMakeLists.txt:85 (add_executable):
[CMake]   No SOURCES given to target: mb_tcp_slave
[CMake] 
[CMake] 
[CMake] CMake Error at C:\Users\arsha\Source\Repos\m-bus\CMakeLists.txt:84 (add_executable):
[CMake]   No SOURCES given to target: mb_master
[CMake] 
[CMake] 
[CMake] CMake Error at C:\Users\arsha\Source\Repos\m-bus\CMakeLists.txt:86 (add_executable):
[CMake]   No SOURCES given to target: mb_rtu_slave
[CMake] `

**Comment by hefloryd** [comment]
The m-bus windows support is currently incomplete. TCP support wll be added
in August.

Den lör 3 juli 2021 06:29r9guy ***@***.***> skrev:

**Comment by hefloryd** [comment]
See PR #4. TCP only, RTU not yet supported.
